import Head from 'next/head'
import { FirstSection, Despre, Servicii, Portofoliu } from '@/Components/Sections/Homepage';
import Page from '@/Components/page';
import { gql } from '@apollo/client';
import client from '@/utils/client';
import { PortfolioItems } from '@/utils/WPQuerys';



export  function Home ( props) {

  console.log("IN Functia Home ===>>>  ",props )
  return (
    <Page>
      <Head>
        <title>Crela </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <FirstSection />
      <Despre />
      <Servicii />
      <Portofoliu {...props} />
    </Page>
  );
}

export default Home

export async function getStaticProps(context) {
const { data } = await client.query({
  query: gql(`query PortfolioItems {
  portfolioItems(first: 90000) {
    nodes {
      excerpt
      featuredImage {
        node {
          altText
          sourceUrl
        }
      }
      title
      slug
      buttonColor {
        buttonColor
      }
      blocksJSON
    }
  }
}`),
});
console.log();

if (!data?.portfolioItems?.nodes){
  return { props: {message: "No Data"}}
}

return { props: { ...data?.portfolioItems?.nodes } };
}




// export async function getStaticPaths(context) {}