import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Navigation } from '@/Components/NavBar/Index'
import { FirstSection, Despre, Servicii, Portofoliu } from '@/Components/Sections/Homepage';
import Page from '@/Components/page';

export default function Home() {
  return (
    <Page>
      <Head>
        <title>Crela </title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        
      
      <FirstSection />
      <Despre />
      <Servicii />
      <Portofoliu />
    </Page>
  );
}
